<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);SYSLIB1054</NoWarn>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CDRIconExtractor.Core\CDRIconExtractor.Core.csproj" />
  </ItemGroup>
</Project>
